services:
  mysql:
    image: mysql:8.0.33
    container_name: youngmyung-mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: inflearn
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 1234
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_general_ci
      TZ: Asia/Seoul
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d

  app:
    container_name: youngmyung-Nodejs-Express
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mysql
    ports:
      - '3000:3000'
    command:
      - bash
      - -c
      - |
        /app/wait-for-it.sh mysql:3306 -s -t 100
        npm run start
    volumes:
      - ./:/app
