services:
  mysql-test:
    image: mysql:8.0.33
    container_name: youngmyung-mysql-test
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: inflearn-test
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    command:
      - --skip-character-set-client-handshake
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
